USE [master]
GO
CREATE DATABASE [EladGroup]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EladGroup', FILENAME = N'I:\Tal\Microsoft SSMS\Installation\MSSQL15.SQLEXPRESS\MSSQL\DATA\EladGroup.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EladGroup_log', FILENAME = N'I:\Tal\Microsoft SSMS\Installation\MSSQL15.SQLEXPRESS\MSSQL\DATA\EladGroup_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [EladGroup] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EladGroup].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [EladGroup] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [EladGroup] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [EladGroup] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [EladGroup] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [EladGroup] SET ARITHABORT OFF 
GO
ALTER DATABASE [EladGroup] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [EladGroup] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [EladGroup] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [EladGroup] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [EladGroup] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [EladGroup] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [EladGroup] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [EladGroup] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [EladGroup] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [EladGroup] SET  DISABLE_BROKER 
GO
ALTER DATABASE [EladGroup] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [EladGroup] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [EladGroup] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [EladGroup] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [EladGroup] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [EladGroup] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [EladGroup] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [EladGroup] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [EladGroup] SET  MULTI_USER 
GO
ALTER DATABASE [EladGroup] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [EladGroup] SET DB_CHAINING OFF 
GO
ALTER DATABASE [EladGroup] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [EladGroup] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [EladGroup] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [EladGroup] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [EladGroup] SET QUERY_STORE = OFF
GO
USE [EladGroup]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE TABLE [dbo].[City](
	[Id] [int] NOT NULL,
	[Name] [varchar](50) NULL,
	[Priority] [int] NOT NULL,
 CONSTRAINT [PK_City] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
